### ISSUE TITLE
Got a traceback  when working with python3.5

### ISSUE THREAD

**Issue by weishen** [bdarnell/torndb#39]
I got the following error when working with python3.
File "/usr/local/lib/python3.5/site-packages/torndb.py", line 138, in query#012    return [Row(itertools.izip(column_names, row)) for row in cursor]#012  File "/usr/local/lib/python3.5/site-packages/torndb.py", line 138, in <listcomp>#012    return [Row(itertools.izip(column_names, row)) for row in cursor]#012AttributeError: module 'itertools' has no attribute 'izip'

For python3, it should use "zip" instead of "itertools.izip"

**Comment by bdarnell** [comment]
Duplicate of #24: this package is not actively maintained, does not support python 3 and is unlikely to receive major updates. Anyone interested in updating it is welcome to fork it under a new name.
